# Generated by Django 6.0.3 on 2026-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('products', '0003_product_activated_at_product_activated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrecord',
            name='location',
        ),
        migrations.AddConstraint(
            model_name='scanrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_first_scan', True)), fields=('product',), name='unique_first_scan_per_product'),
        ),
    ]
