# Generated by Django 6.0.3 on 2026-06-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_scanrecord_location_and_more'),
        ('products', '0004_catalogproduct_product_catalog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['customer_email', '-scanned_at'], name='authenticat_custome_8b4917_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['is_first_scan', '-scanned_at'], name='authenticat_is_firs_37a6dd_idx'),
        ),
    ]
