# Generated by Django 6.0.3 on 2026-06-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_catalogproduct_product_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
